name = "whiteboard-the-conf"
compatibility_date = "2023-10-16"

[[d1_databases]]
binding = "DB"
database_name = "whiteboard-the-conf"
database_id = "b04e0049-2b5f-4697-9e53-4840368cba63"
preview_database_id = "DB"
